<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6JHUUG8" failures="0" tests="2" name="com.Maven.TimeOut1" time="2.051" errors="1" timestamp="2023-09-09T22:44:04 IST" skipped="0">
  <testcase classname="com.Maven.TimeOut1" name="methodA" time="2.046">
    <error message="Method com.Maven.TimeOut1.methodA() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.Maven.TimeOut1.methodA() didn't finish within the time-out 2000
at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:64)
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at java.base@17.0.3/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base@17.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- methodA -->
  <testcase classname="com.Maven.TimeOut1" name="methodC" time="0.005"/>
</testsuite> <!-- com.Maven.TimeOut1 -->
